puts "The students of Villains Academy"
puts "---------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Micheal Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "T-2000"
puts "Freddy Krueger"
puts "The Jocker"
puts "Joffrey Baratheon"
puts "Norman  Bates"
